# Generated by Django 2.2.7 on 2019-11-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sygma', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMMITMENT', 'Commitment'), ('REPORT', 'Report')], max_length=50)),
                ('due', models.DateTimeField(null=True)),
                ('details', models.CharField(max_length=5000, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sygma.Grant')),
            ],
        ),
    ]
