# Generated by Django 2.2.7 on 2019-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sygma', '0003_obligation'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='title',
            field=models.CharField(default='lol', max_length=250),
            preserve_default=False,
        ),
    ]
