# Generated by Django 2.2.7 on 2019-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sygma', '0004_obligation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('LOISENT', 'Letter of Intent Sent'), ('LOIACCEPTED', 'Letter of Intent Accepted'), ('INPROGRESS', 'Application in progress'), ('SUBMITTED', 'Submitted'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('RECEIVED', 'Received')], max_length=50),
        ),
    ]
