# Generated by Django 2.2.7 on 2019-12-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sygma', '0005_auto_20191209_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligation',
            name='kind',
        ),
    ]
